application: 
  host: rewura.gleeze.com

ingress: 
  api: 
    fullName: nginx-ingress-api-dev
  oauth2: 
    fullName: nginx-ingress-oauth2-dev
  frontend: 
    fullName: nginx-ingress-frontend-dev
  frontend_oauth: 
    fullName: nginx-ingress-frontend-oauth-dev

service:
  frontend: 
    serviceName: rewura-frontend-service
    port: 8301
    portType: ClusterIP
    image: gabendockerzone/rewura-frontend:59264d0
    componentSelector: web
  #postgres: 
  #  serviceName: postgres-service
  #  port: 5432
  #  portType: NodePort
  #  image: postgres
  #  componentSelector: postgres
  authorization: 
    serviceName: rewura-authorization-service
    port: 8302
    portType: ClusterIP
    image: gabendockerzone/authorization-service:e41e229
    componentSelector: server
  file: 
    serviceName: rewura-file-upload-service
    port: 8303
    portType: ClusterIP
    image: gabendockerzone/file-upload-service:20aad91
    componentSelector: server-file
  hobby: 
    serviceName: rewura-hobby-service
    port: 8304
    portType: ClusterIP
    image: gabendockerzone/hobby-service:98b623c
    componentSelector: server-hobby

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80