application: 
  host: v2.rewura.com

ingress: 
  api: 
    fullName: nginx-ingress-api-dev-v2
  oauth2: 
    fullName: nginx-ingress-oauth2-dev-v2
  frontend: 
    fullName: nginx-ingress-frontend-dev-v2
  frontend_oauth: 
    fullName: nginx-ingress-frontend-oauth-dev-v2
  frontend_assets: 
    fullName: nginx-frontend-assets-dev-v2

service:
  frontend: 
    serviceName: rewura-frontend-service
    port: 8301
    portType: ClusterIP
    image: gabendockerzone/rewura-frontend-v2:e144947
    componentSelector: web
  authorization: 
    serviceName: rewura-authorization-service
    port: 8302
    portType: ClusterIP
    image: gabendockerzone/authorization-service:e41e229
    componentSelector: server
    environment: 
      - name: 'DATASOURCE_URL'
        value: 'jdbc:postgresql://postgres-postgresql.managed/postgres?currentSchema=prod_rewura_auth,public,pg_catalog'
      - name: 'DATASOURCE_USER'
        value: 'postgres'
      - name: 'DATASOURCE_PASSWORD'
        value: 'postgres'
      - name: GOOGLE_CLIENT_ID
        value: '912050282042-ais7fbu2uns1u3go9eoe6l8iaiv3iruo.apps.googleusercontent.com'
      - name: GOOGLE_CLIENT_SECRET
        value: '5Ex-92yP7Q1YU_TmgtVXiYR5'
      - name: FACEBOOK_CLIENT_ID
        value: '1670650839666976'
      - name: FACEBOOK_CLIENT_SECRET
        value: '97e1e2cfb217a1730563ad1361bda51c'
  file: 
    serviceName: rewura-file-upload-service
    port: 8303
    portType: ClusterIP
    image: gabendockerzone/file-upload-service:20aad91
    componentSelector: server-file
  hobby: 
    serviceName: rewura-hobby-service
    port: 8304
    portType: ClusterIP
    image: gabendockerzone/hobby-service:b35f572
    componentSelector: server-hobby
    environment: 
      - name: 'DATASOURCE_URL'
        value: 'jdbc:postgresql://postgres-postgresql.managed/postgres?currentSchema=prod_rewura,public,pg_catalog'
      - name: 'DATASOURCE_USER'
        value: 'postgres'
      - name: 'DATASOURCE_PASSWORD'
        value: 'postgres'
      - name: AUTH_SERVICE_ENDPOINT
        value: 'http://rewura-authorization-service:8302/api/auth'
      - name: TEST_MODE_ENABLED
        value: false

  #postgres: 
  #  serviceName: postgres-service
  #  port: 5432
  #  portType: NodePort
  #  image: postgres
  #  componentSelector: postgres

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80